C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\000000_black.bmp"    -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\0000FF_blue.bmp"     -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\00FF00_green.bmp"    -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\00FF7F_lime.bmp"     -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\00FFFF_cyan.bmp"     -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\00007F_navy.bmp"     -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\007F00_forest.bmp"   -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\007F7F_teal.bmp"     -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\007FFF_cerulean.bmp" -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\7F0000_scarlet.bmp"  -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\7F00FF_purple.bmp"   -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\7F007F_maroon.bmp"   -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\7F7F00_olive.bmp"    -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\7F7F7F_grey.bmp"     -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\7F7FFF_violet.bmp"   -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\7FFF00_grass.bmp"    -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\7FFF7F_spring.bmp"   -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\7FFFFF_sky.bmp"      -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\FF0000_red.bmp"      -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\FF00FF_magenta.bmp"  -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\FF007F_hotpink.bmp"  -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\FF7F00_orange.bmp"   -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\FF7F7F_salmon.bmp"   -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\FF7FFF_pink.bmp"     -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\FFFF00_yellow.bmp"   -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\FFFF7F_gold.bmp"     -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\FFFFFF_white.bmp"    -o "C:\Images\7thSquares_v3_12b" -d RGB_U12_RGB-SMPTE-2110

C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\000000_black.bmp"    -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\0000FF_blue.bmp"     -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\00FF00_green.bmp"    -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\00FF7F_lime.bmp"     -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\00FFFF_cyan.bmp"     -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\00007F_navy.bmp"     -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\007F00_forest.bmp"   -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\007F7F_teal.bmp"     -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\007FFF_cerulean.bmp" -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\7F0000_scarlet.bmp"  -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\7F00FF_purple.bmp"   -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\7F007F_maroon.bmp"   -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\7F7F00_olive.bmp"    -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\7F7F7F_grey.bmp"     -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\7F7FFF_violet.bmp"   -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\7FFF00_grass.bmp"    -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\7FFF7F_spring.bmp"   -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\7FFFFF_sky.bmp"      -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\FF0000_red.bmp"      -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\FF00FF_magenta.bmp"  -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\FF007F_hotpink.bmp"  -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\FF7F00_orange.bmp"   -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\FF7F7F_salmon.bmp"   -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\FF7FFF_pink.bmp"     -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\FFFF00_yellow.bmp"   -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\FFFF7F_gold.bmp"     -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB
C:\7thSense\FFMPEG27th\bin\FFmpeg2SeventhApp.exe -i "C:\Images\BmpSquares_v3\FFFFFF_white.bmp"    -o "C:\Images\7thSquares_v3_8b" -d RGB_U8_RGB